name = "d_lan_website"
version = "1.0.0"
description = "The D-LAN website"

[dependencies]
mist = ">= 6.0.0 and < 7.0.0"
wisp = ">= 2.2.2 and < 3.0.0"
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_json = ">= 3.0.1 and < 4.0.0"
gleam_crypto = ">= 1.5.0 and < 2.0.0"
tom = ">= 2.1.0 and < 3.0.0"
simplifile = ">= 2.5.0 and < 3.0.0"
lustre = ">= 5.7.1 and < 6.0.0"
gleam_time = ">= 1.8.0 and < 2.0.0"
gleam_regexp = ">= 1.1.1 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
radiate = ">= 1.0.0 and < 2.0.0"
