/**
  * Some common messages.
  * All string are encoded in UTF-8.
  */

syntax = "proto3";

package Protos.Common;

message Null {
}

enum TriState {
   TS_NO_CHANGE = 0;
   TS_TRUE = 1;
   TS_FALSE = 2;
}

message Error {
   string message = 1;
}

message Language {
   string lang = 1; // ISO-639 (two letters).
   string country = 2; // ISO-3166.
}

// To identify a chunk or a user.
message Hash {
   bytes hash = 1; // 28 bytes. If it doesn't exist the hash is null.
}

message IP {
   enum Type {
      IPv4 = 0;
      IPv6 = 1;
   }
   Type type = 1;
   bytes ip = 2; // if type == IPv4 -> 4 bytes. If type == IPv6 -> 16 bytes. Big endian.
}

// A shared entry matches an existing handle, thus it's optional to have the complete path to it.
message SharedEntry {
   Hash id = 1; // Identify a shared entry.

   // A name to identify the shared entry by human.
   // It may correspond to the name of the shared entry itself (directory or filename).
   // It may be used when creating the directories of a new downloading file.
   // It may be empty. In this case the directory name or filename is used instead (from 'SharedEntry::path').
   string shared_name = 2;

   string path = 3; // A dir must end with a "/" otherwise it's a file.
}

// Used for a directory or a file.
message Entry {
   enum Type {
      FILE = 0;
      DIR = 1;
   }
   Type type = 1;

   // Relative path from the sharing entry. For example : "Videos/My cat/".
   // A shared directory, shared file or a root entry has an empty path.
   // It doesn't contain the entry name. See 'name'.
   string path = 2;

   string name = 3; // Directory name or filename. For example: "MyLOLCat.avi". A shared dir/file has an empty name.
   uint64 size = 4; // [bytes]. For the directory it's the sum of all sub-items.

   // The shared entry of the entry. If the entry is a shared file the shared_entry must be the same file.
   SharedEntry shared_entry = 5;

   bool exists = 6; // [default = true] An entry may not yet be created.

   // Only for DIR type.
   bool is_empty = 7; // [default = true] Warning: a directory can be not empty and has a size of 0.

   // Only for FILE type:
   // optional string mime_type = 9; // The mime type of the file. TODO: uncomment when #243 is implemented.

   // The number of chunk must always correspond to the size of the file. Unknown chunks are empty.
   repeated Hash chunks = 8;
}

message Entries
{
   repeated Common.Entry entries = 1;
}

enum DownloadStatus {
   QUEUED = 0x0;
   GETTING_THE_HASHES = 0x1;
   DOWNLOADING = 0x2;
   COMPLETE = 0x3;
   PAUSED = 0x4;
   DELETED = 0x5; // Should not be seen by the user.

   UNKNOWN_PEER_SOURCE = 0x10; // The source peer isn't found and we don't have all the hashes.
   ENTRY_NOT_FOUND = 0x11; // The entry isn't found in the source peer shared directories.
   NO_SOURCE = 0x12; // All the hashes are known but one ore more chunk are not present among the other peers.

   // All the following status will pause the download.
   NO_SHARED_DIRECTORY_TO_WRITE = 0x20;
   NO_ENOUGH_FREE_SPACE = 0x21;
   UNABLE_TO_CREATE_THE_FILE = 0x22;
   UNABLE_TO_CREATE_THE_DIRECTORY = 0x30;
   UNABLE_TO_RETRIEVE_THE_HASHES = 0x23;

   TRANSFER_ERROR = 0x24;
   UNABLE_TO_OPEN_THE_FILE = 0x25;
   FILE_IO_ERROR = 0x26;
   FILE_NON_EXISTENT = 0x27;
   GOT_TOO_MUCH_DATA = 0x28;
   HASH_MISMATCH = 0x29;

   REMOTE_SCANNING_IN_PROGRESS = 0x31; // When a remote file or directory is being scanned it's not possible to browse it or download it.
   LOCAL_SCANNING_IN_PROGRESS = 0x33; // When a local directory is being scanned it's not possible to download into.
   UNABLE_TO_GET_ENTRIES = 0x32;
}

message FindPattern {
   string pattern = 2;
   uint64 min_size = 3; // [B]. 0 means there is no minimum size. Only for files.
   uint64 max_size = 4; // [B]. 0 means there is no maximum size. Only for files.
   repeated string extension_filters = 5; // Only files that match one of the given extension will be returned.
   enum Category {
      FILE_DIR = 0;
      FILE = 1;
      DIR = 2;
   }
   Category category = 6; // [default = FILE_DIR].
}

// A result following a search.
// Entries may not be sorted in any particular way.
// See 'Core.Find' and 'GUI.Search' for more information.
message FindResult {
   message EntryLevel {
      uint32 level = 1;
      Entry entry = 2; // The entry must have the field 'shared_dir'.
   }
   uint64 tag = 1;
   repeated EntryLevel entries = 2;
   Common.Hash peer_id = 3;
}

// 'id' is randomly generated for each message.
message ChatMessage {
   uint64 id = 1;
   string message = 2;
   Common.Hash peer_id = 3;
   uint64 time = 4; // In [ms] since Epoch.
   string peer_nick = 5;
   string chat_room = 6;
   repeated Common.Hash peer_ids_answer = 7;
}

// All messages must belong to the same chat room (or from no room if they are from the main chat).
// The messages are always sorted from oldest to youngest.
message ChatMessages {
   repeated ChatMessage messages = 1;
}

message Interface {
   message Address {
      enum Protocol {
         IPv6 = 0;
         IPv4 = 1;
      }
      string address = 1;
      Protocol protocol = 2;
      bool listened = 3;
   }
   uint32 id = 1;
   string name = 2;
   repeated Address addresses = 3;
   bool is_up = 4;
}
