#ifndef UPLOADMANAGER_GLOBAL_H
#define UPLOADMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UPLOADMANAGER_LIBRARY)
#  define UPLOADMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define UPLOADMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // UPLOADMANAGER_GLOBAL_H
