#ifndef REMOTECONTROLMANAGER_GLOBAL_H
#define REMOTECONTROLMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(REMOTECONTROLMANAGER_LIBRARY)
#  define REMOTECONTROLMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define REMOTECONTROLMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // REMOTECONTROLMANAGER_GLOBAL_H
