#ifndef PEERMANAGER_GLOBAL_H
#define PEERMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PEERMANAGER_LIBRARY)
#  define PEERMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PEERMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PEERMANAGER_GLOBAL_H
